### ISSUE TITLE
GitHub Action doesn't respect Pull Requests and it's branches while validating.

### ISSUE THREAD

**Issue by AL2009man** [hedge-dev/UnleashedRecomp#1311]
It appears that GitHub Action on the .yml validate doesn't include something like this:

```
on:
  pull_request:
    branches:
      - main
    types:
      - edited
      - opened
      - synchronize
```

While it's fine for releases, Git Actions will instead use `main` as opposed to using the pull request's changes for testing purposes. 

This caused several hours of troubleshooting when trying to test the changes before merging to Master. Had to resort to building the file myself due to it.
